/**
 * Course: COMP 426
 * Assignment: a05
 *
 * This file defines data to be rendered to the page.
 */


/**
 * Represents a list of heroic users
 */
const heroicData = [{
    id: 0,
    name: "Hibachi & Co",
    address: "155 E Franklin St, Chapel Hill, NC 27514",
    hours: "11AM-10PM",
    img: "r_icons/hibachi.png",
    color: "black",
    backgroundColor: "#E13C28",
    kosher_options: false,
    gf: true,
    nut_friendly: true,
    vegan: false,
}, {
    id: 1,
    name: "Moe's Southwest Grill",
    address: "110 W Franklin St, Chapel Hill, NC 27516",
    hours: "11AM-10PM",
    img: "r_icons/moes.png",
    color: "black",
    backgroundColor: "#B4F9BB",
    kosher_options: false,
    gf: true,
    nut_friendly: true,
    vegan: false,
}, {
    id: 2,
    name: "Chipotle Mexican Grill",
    address: "301 W Franklin St, Chapel Hill, NC 27516",
    hours: "11AM-10PM",
    img: "r_icons/chipoltle.png",
    color: "black",
    backgroundColor: "#F9B4B4",
    kosher_options: true,
    gf: true,
    nut_friendly: true,
    vegan: false,
}, {
    id: 3,
    name: "The Pizza Press",
    address: "133 W Franklin St Suite 120 Suite 120, Chapel Hill, NC 27516",
    hours: "11AM-10PM",
    img: "r_icons/pizzapress.png",
    color: "black",
    backgroundColor: "#DED9D7",
    kosher_options: false,
    gf: false,
    nut_friendly: true,
    vegan: false,
}, {
    id: 4,
    name: "Bandito's Mexican Cafe",
    address: "159 1/2 E Franklin St, Chapel Hill, NC 27514",
    hours: "11AM-10PM",
    img: "r_icons/banditos.jpg",
    color: "black",
    backgroundColor: "#F8F9B4",
    kosher_options: false,
    gf: true,
    nut_friendly: true,
    vegan: false,
}, {
    id: 5,
    name: "Ms. Mong",
    address: "163 E Franklin St, Chapel Hill, NC 27514",
    hours: "11AM-10PM",
    img: "r_icons/mong.png",
    color: "black",
    backgroundColor: "#B8B4F9",
    kosher_options: false,
    gf: false,
    nut_friendly: false,
    vegan: false,
}, {
    id: 6,
    name: "Sutton's Drug Store",
    address: "159 E Franklin St, Chapel Hill, NC 27514",
    hours: "11AM-10PM",
    img: "r_icons/suttons.jpg",
    color: "black",
    backgroundColor: "#E2B4F9",
    kosher_options: false,
    gf: false,
    nut_friendly: true,
    vegan: false,
}, {
    id: 7,
    name: "Panera Bread",
    address: "213 W Franklin St, Chapel Hill, NC 27516",
    hours: "11AM-10PM",
    img: "r_icons/panera.png",
    color: "black",
    backgroundColor: "#F9D9B4 ",
    kosher_options: true,
    gf: false,
    nut_friendly: true,
    vegan: true,
}, {
    id: 8,
    name: "Chabad House",
    address: "Somewhere on Malette St.",
    hours: "11AM-10PM",
    img: "r_icons/chabad.jpg",
    color: "black",
    backgroundColor: "#B4E6F9",
    kosher_options: true,
    gf: false,
    nut_friendly: false,
    vegan: true,
}
];
